openapi: 3.0.0
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
    PSUCreateResponse:
      type: object
      properties:
        url:
          type: string
    GetRecordList:
      type: object
      properties:
        sortorder:
          type: string
        pagination:
          type: string
        startkey:
          type: object
          properties:
            bucketname:
              type: string
            uploadtimedate:
              type: string
    GetRecordListResponse:
      type: object
      properties:
        Items:
          type: object
          properties:
            bucketname:
              type: string
            objectname:
              type: string
            filesize:
              type: string
            mimetype:
              type: string
            uploadtimedate:
              type: string
        Count:
          type: number
        ScannedCount:
          type: number
        LastEvaluatedKey:
          type: object
          properties:
            bucketname:
              type: string
            uploadtimedate:
              type: string
    GetRecord:
      type: object
      properties:
        name:
          type: string
    GetRecordResponse:
      type: object
      properties:
        Items:
          type: object
          properties:
            bucketname:
              type: string
            objectname:
              type: string
            filesize:
              type: string
            mimetype:
              type: string
            uploadtimedate:
              type: string
        Count:
          type: number
        ScannedCount:
          type: number
  securitySchemes: {}
info:
  title: Serverless-DynamoDB-Demo
  description: >-
    Uses the Serverless Framework to create a (Lambda & API Gateway based)
    serverless API to record S3 objects in DynamoDB
  version: '1.0'
paths:
  //v1/genpsu:
    post:
      operationId: genpsu
      summary: Generate Pre-Signed URL
      description: Creates an S3 pre-signed URL
      responses:
        '201':
          description: A pre-signed URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PSUCreateResponse'
        '500':
          description: An error message when creating a pre-signed URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  //v1/getlist:
    post:
      operationId: getrecordlist
      summary: Retrieve a List of S3 Objects from DynamoDB
      description: >-
        Generates a list of S3 objects and their attributes sorted by upload
        time
      responses:
        '201':
          description: A list of S3 objects and attributes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRecordListResponse'
        '500':
          description: An error occurred when fetching the list of objects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  //v1/getitem:
    post:
      operationId: getrecord
      summary: Retrieve an S3 Object from DynamoDB
      description: Generates an S3 objects and its attributes
      responses:
        '201':
          description: An S3 object and attributes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRecordResponse'
        '500':
          description: An error occurred when fetching the object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
